### ISSUE TITLE
Error in console when changing resource packs

### ISSUE THREAD

**Issue by Shahelion** [LordPINE/witchesdreams#1] opened 2023-09-10 23:12 UTC
Appeared in the console near the end of all of the other messages that print when you activate/change texture packs.

[15:22:57] [Client thread/WARN]: Unable to parse metadata section of resourcepack: FMLFileResourcePack:"Witches Dreams"
com.google.gson.JsonParseException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 3 column 41
	at net.minecraft.client.resources.AbstractResourcePack.func_110596_a(AbstractResourcePack.java:81) ~[bqn.class:?]
	at net.minecraft.client.resources.AbstractResourcePack.func_135058_a(AbstractResourcePack.java:66) ~[bqn.class:?]
	at net.minecraft.client.resources.LanguageManager.func_135043_a(LanguageManager.java:50) [brr.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:622) [bao.class:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.func_146284_a(SourceFile:151) [bgf.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) [bdw.class:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.func_73864_a(SourceFile:158) [bgf.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) [bdw.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 3 column 41
	at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
	at net.minecraft.client.resources.AbstractResourcePack.func_110596_a(AbstractResourcePack.java:77) ~[bqn.class:?]
	... 21 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 3 column 41
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[TypeAdapters$25.class:?]
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667) ~[TypeAdapters$25.class:?]
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[TypeAdapters$25.class:?]
	at com.google.gson.internal.Streams.parse(Streams.java:44) ~[Streams.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
	at net.minecraft.client.resources.AbstractResourcePack.func_110596_a(AbstractResourcePack.java:77) ~[bqn.class:?]
	... 21 more

**Comment by LordPINE** [comment] 2024-02-07 09:34
Should be fixed in the latest version, it was caused by a small mistake in the gradle.properties.

**Closed as completed by LordPINE** 2024-02-07 09:34 UTC
